name: CP Test Site
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63216
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d6e71'
    - '#3a3a3c'
    - '#ed217c'
    - '#40b649'
    - '#23a9e1'
  brandStrength: 0.4375
  lightness: 0.46930548502132297
  saturation: 0.6875
  rhythmicContrast: 0.5523898045066744
purpose: []
